### ISSUE TITLE
Parsing fails if a value contains delimiter character

### ISSUE THREAD

**Issue by dulezmaj** [atifaziz/yax#5]
The following code

```
var lines = new[]
{
    "ColumnA,\"ColumnB\"",
    "\"Value 1\",\"Value \"2\"",
};

var rows =
    lines.ParseCsv()
         .ToArray();

```

fails with error message: `Missing delimiter (line #2, col #19).`

A CSV file with the same content is successfully opened by Excel.

**Comment by atifaziz** [comment]
The error is correct when you consider the value of `ColumnB` on line 2 and you expect _quoted fields_:

    ColumnA,"ColumnB"
    "Value 1","Value "2"

Dsv thinks that `"Value "2"` ended as `"Value "` since the quotes are balanced there. The `2"` _should_ belong to the next field but clearly a comma is missing and so you get the error about a missing delimiter.

For sake of simplicity, Dsv is not designed to deal with and recover from malformed CSV formatting. Excel might succeed because it might be have more tolerance built into it. That said, just looking at the example you gave, one can't tell if quoting is expected or not. If _quotes are part of the field value_ then using `ParseCsv` is the wrong method, because it simply calls `ParseDsv` with `Format.Csv` and `Format.Csv` is configured to assume comma as the delimiter, fields to be quoted and that quote escapes quote (`""` &rarr; `"`). If you call `ParseDsv` with `Format.UnquotedCsv`:

```c#
var rows =
    lines.ParseDsv(Format.UnquotedCsv)
         .ToArray();
foreach (var row in rows)
    Console.WriteLine((row[0], row[1]).ToString());
```

then you'll be able to parse the given CSV and output of above will be as follows:

    (ColumnA, "ColumnB")
    ("Value 1", "Value "2")

But notice now that the quotes are part of the field value. Whether that's correct or the CSV is malformed, you now have a chance to fix those problems post-parsing.

I am going to close this as by-design. If you feel I've misinterpreted the issue then feel free to re-open.

**Comment by dulezmaj** [comment]
Thanks, all clear. I wasn't sure on the correctness of malformed CSV because some online validators mark it as correct. Preprocessing lines before parsing might help actually.
